<a href="https://colab.research.google.com/github/adrianosima/Adriano_Simao/blob/main/Analise_data_set_unicornio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

import warnings

warnings.filterwarnings('ignore')

%time

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.29 µs

In [59]:
#Ler os dados
data_base = pd.read_csv('/content/unicorns till sep 2022.csv')

#verificar a dimensão do db
data_base.shape

(1186, 7)

In [60]:
#Verificar os 5 primeiros reginstros
data_base.head()

,Company,Valuation ($B),Date Joined,Country,City,Industry,Investors
0,ByteDance,$140,4/7/2017,China,Beijing,Artificial intelligence,"Sequoia Capital China, SIG Asia Investments, S..."
1,SpaceX,$127,12/1/2012,United States,Hawthorne,Other,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,SHEIN,$100,7/3/2018,China,Shenzhen,E-commerce & direct-to-consumer,"Tiger Global Management, Sequoia Capital China..."
3,Stripe,$95,1/23/2014,United States,San Francisco,Fintech,"Khosla Ventures, LowercaseCapital, capitalG"
4,Canva,$40,1/8/2018,Australia,Surry Hills,Internet software & services,"Sequoia Capital China, Blackbird Ventures, Mat..."

In [61]:
#Renomeando colunas
data_base.rename(
    columns = {
        'Company': 'Empresa',
        'Valuation ($B)': 'Valor ($B)',
        'Date Joined': "Data de Adesão",
        'Country': "País",
        'City ': "Cidade",
       'Industry': "Industria",
        'Investors': "Investidores"
    }, inplace = True #Aplica as mudanças na base de origem
)

#verificar cada coluna
data_base.columns

Index(['Empresa', 'Valor ($B)', 'Data de Adesão', 'País', 'City ', 'Industria',
       'Investidores'],
      dtype='object')

In [62]:
#Verificando o tipo da informação
data_base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Empresa         1186 non-null   object
 1   Valor ($B)      1186 non-null   object
 2   Data de Adesão  1186 non-null   object
 3   País            1186 non-null   object
 4   City            1186 non-null   object
 5   Industria       1186 non-null   object
 6   Investidores    1168 non-null   object
dtypes: object(7)
memory usage: 65.0+ KB

In [63]:
#Verificando quantos e aonde estão localizados os campos nulos
data_base.isnull().sum()

Empresa            0
Valor ($B)         0
Data de Adesão     0
País               0
City               0
Industria          0
Investidores      18
dtype: int64

In [67]:
#Verificando de forma grafica
plt.figure(figsize=(15,6))
plt.title('Campos nulos')
sns.heatmap( data_base.isnull() );